# Generated by Django 5.2.13 on 2026-04-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCache',
            fields=[
                ('url_key', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('website_name', models.TextField(blank=True, null=True)),
                ('trust_score', models.IntegerField(blank=True, null=True)),
                ('risk_level', models.TextField(blank=True, null=True)),
                ('confidence_level', models.TextField(blank=True, null=True)),
                ('analysis_json', models.JSONField()),
                ('access_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField()),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'website_cache',
            },
        ),
    ]
